language: go
go:
  - "1.13.1"
  - master

script:
    - go build
    - golangci-lint --version
    - golangci-lint run
    - go test -v ./...
    - go test -v -covermode=count -coverprofile=coverage.out ./diff
    - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
